package com.empresa.proyecto.vaadin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class PanelLogout extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Panel pnlLogout;

	@AutoGenerated
	private VerticalLayout layoutLogout;

	@AutoGenerated
	private Button btnLinkCerrar;

	@AutoGenerated
	private Label lblClave;

	@AutoGenerated
	private Label lblUsuario;

	@AutoGenerated
	private VerticalLayout pnlLogo;

	@AutoGenerated
	private Embedded imgLogout;

	private static final long serialVersionUID = -2572090539149417779L;
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	public PanelLogout() {

		buildMainLayout();
		setCompositionRoot(mainLayout);		
		lblUsuario.setValue("");
		lblUsuario.setContentMode(Label.CONTENT_XHTML);
		lblUsuario.setValue("<h1 style='color:#0065B7;'>Demo Vaadin 6</h1>");
		lblClave.setValue("");
		lblClave.setContentMode(Label.CONTENT_XHTML);
		lblClave.setValue("<h2 style='color:#0065B7;'>Sesión Terminada.</h2>");
		btnLinkCerrar.setStyleName("link");
		btnLinkCerrar.setVisible(true);
		activarLink();
	}

	private void activarLink(){
		
		btnLinkCerrar.addListener(new Button.ClickListener() {

			private static final long serialVersionUID = -1549238415860933027L;

			public void buttonClick(Button.ClickEvent event) {
				getWindow().getApplication().close();
		    }
		});
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("400px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("400px");
		
		// pnlLogout
		pnlLogout = buildPnlLogout();
		mainLayout.addComponent(pnlLogout);
		mainLayout.setComponentAlignment(pnlLogout, new Alignment(24));
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPnlLogout() {
		// common part: create layout
		pnlLogout = new Panel();
		pnlLogout.setImmediate(false);
		pnlLogout.setWidth("900px");
		pnlLogout.setHeight("300px");
		
		// layoutLogout
		layoutLogout = buildLayoutLogout();
		pnlLogout.setContent(layoutLogout);
		
		return pnlLogout;
	}

	@AutoGenerated
	private VerticalLayout buildLayoutLogout() {
		// common part: create layout
		layoutLogout = new VerticalLayout();
		layoutLogout.setImmediate(false);
		layoutLogout.setWidth("100.0%");
		layoutLogout.setHeight("100.0%");
		layoutLogout.setMargin(false);
		
		// pnlLogo
		pnlLogo = buildPnlLogo();
		layoutLogout.addComponent(pnlLogo);
		layoutLogout.setComponentAlignment(pnlLogo, new Alignment(33));
		
		// lblUsuario
		lblUsuario = new Label();
		lblUsuario.setImmediate(false);
		lblUsuario.setWidth("-1px");
		lblUsuario.setHeight("-1px");
		lblUsuario.setValue("Demo Vaadin 6");
		layoutLogout.addComponent(lblUsuario);
		layoutLogout.setComponentAlignment(lblUsuario, new Alignment(48));
		
		// lblClave
		lblClave = new Label();
		lblClave.setImmediate(false);
		lblClave.setWidth("-1px");
		lblClave.setHeight("-1px");
		lblClave.setValue("Sesión Terminada.");
		layoutLogout.addComponent(lblClave);
		layoutLogout.setComponentAlignment(lblClave, new Alignment(20));
		
		// btnLinkCerrar
		btnLinkCerrar = new Button();
		btnLinkCerrar.setCaption("Cerrar");
		btnLinkCerrar.setImmediate(true);
		btnLinkCerrar.setWidth("-1px");
		btnLinkCerrar.setHeight("-1px");
		layoutLogout.addComponent(btnLinkCerrar);
		layoutLogout.setComponentAlignment(btnLinkCerrar, new Alignment(24));
		
		return layoutLogout;
	}

	@AutoGenerated
	private VerticalLayout buildPnlLogo() {
		// common part: create layout
		pnlLogo = new VerticalLayout();
		pnlLogo.setImmediate(false);
		pnlLogo.setWidth("464px");
		pnlLogo.setHeight("91px");
		pnlLogo.setMargin(true);
		
		// imgLogout
		imgLogout = new Embedded();
		imgLogout.setImmediate(false);
		imgLogout.setWidth("-1px");
		imgLogout.setHeight("-1px");
		imgLogout.setSource(new ThemeResource("img/goodbye.jpg"));
		imgLogout.setType(1);
		imgLogout.setMimeType("image/jpg");
		pnlLogo.addComponent(imgLogout);
		pnlLogo.setComponentAlignment(imgLogout, new Alignment(20));
		
		return pnlLogo;
	}	
}
