package com.empresa.proyecto.vaadin;

import java.util.List;

import static com.empresa.proyecto.util.Constante.MENU;

import com.empresa.proyecto.bean.Opcion;
import com.empresa.proyecto.bean.Usuario;
import com.empresa.proyecto.util.Constante;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;


public class PanelPrincipal extends CustomComponent  implements Command  {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private VerticalLayout mainLayoutContainer;

	@AutoGenerated
	private Label lblPie;

	@AutoGenerated
	private VerticalLayout pnlContenido;

	@AutoGenerated
	private VerticalLayout pnlCabecera;

	@AutoGenerated
	private VerticalLayout pnlTitulo;

	@AutoGenerated
	private Label lblTituloPanel;

	@AutoGenerated
	private MyMenuBar mnuPrincipal;

	private Usuario usuario;
	
	private MenuItem mniUsuario;
	private MenuItem mniCerrarSesion;
	
	private static final long serialVersionUID = -5141799546036721967L;

	public PanelPrincipal() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}
	
	public PanelPrincipal(Usuario usuario){
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
		lblTituloPanel.setValue("usuario=" + usuario.getNombre());
		lblTituloPanel.setContentMode(Label.CONTENT_XHTML);
		lblPie.setValue(Constante.NOMBRE_SISTEMA + " " + Constante.VERSION +" hecho por " + Constante.NOMBRE_EMPRESA);
		this.usuario = usuario;
	}
	
	public void prepararPanelPrincipal(final List<Opcion> listaOpciones){
		
		mniUsuario = mnuPrincipal.addItem(usuario.getNombre(), new ThemeResource("../runo/icons/16/user.png"), null);
		mniCerrarSesion = mniUsuario.addItem("Cerrar Sesión", new ThemeResource("../runo/icons/16/cancel.png"),this);
		
		MenuBar.Command mycommand = new MenuBar.Command() {

			private static final long serialVersionUID = 1L;

			public void menuSelected(MenuItem selectedItem) {
				
				String titulo = "Sin título";
				String width = "-1.0";
				MyComponent myComponent = null;
				Window harecWindow = new Window();
				
				switch(selectedItem.getText()){
					
					case MENU.MANT_EMPLEADOS: 
						titulo = MENU.MANT_EMPLEADOS;
						width = "700px";
						myComponent = new PanelEmpleados(listaOpciones, "300px");
						break;
					
					case MENU.MANT_ACCESOS_PERFILES: break;
					
					case MENU.MANT_ACCESOS_FUNCIONALIDAD: break;
				
					case MENU.REPOR_GENERAL: break;
				}
				
				if(myComponent!=null){
					
					harecWindow.addComponent(myComponent);
					
					harecWindow.setCaption(titulo);
					harecWindow.setWidth(width);
					
					getWindow().addWindow(harecWindow);
				}
		    }  
		};
		        
		MenuBar.MenuItem manteminientos = mnuPrincipal.addItem(MENU.MANTS, null, null);
		manteminientos.addItem(MENU.MANT_EMPLEADOS, null, mycommand);
		MenuBar.MenuItem acceso = manteminientos.addItem(MENU.MANT_ACCESOS, null, mycommand);
		acceso.addItem(MENU.MANT_ACCESOS_PERFILES, null, mycommand);
		acceso.addItem(MENU.MANT_ACCESOS_FUNCIONALIDAD, null, mycommand);
		
		MenuBar.MenuItem reportes = mnuPrincipal.addItem(MENU.REPORTES, null, null);
		reportes.addItem(MENU.REPOR_GENERAL, null, mycommand);
		 
	}
	
	@Override
	public void menuSelected(MenuItem selectedItem) {
		
		if(selectedItem.equals(mniCerrarSesion)){
    		PanelLogout panelLogout= new PanelLogout();
    		mainLayout.removeAllComponents();
    		mainLayout.addComponent(panelLogout);
		}
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// mainLayoutContainer
		mainLayoutContainer = buildMainLayoutContainer();
		mainLayout.addComponent(mainLayoutContainer);
		mainLayout.setExpandRatio(mainLayoutContainer, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayoutContainer() {
		// common part: create layout
		mainLayoutContainer = new VerticalLayout();
		mainLayoutContainer.setImmediate(false);
		mainLayoutContainer.setWidth("100.0%");
		mainLayoutContainer.setHeight("100.0%");
		mainLayoutContainer.setMargin(false);
		
		// pnlCabecera
		pnlCabecera = buildPnlCabecera();
		mainLayoutContainer.addComponent(pnlCabecera);
		
		// pnlContenido
		pnlContenido = new VerticalLayout();
		pnlContenido.setImmediate(false);
		pnlContenido.setWidth("100.0%");
		pnlContenido.setHeight("100.0%");
		pnlContenido.setMargin(false);
		mainLayoutContainer.addComponent(pnlContenido);
		mainLayoutContainer.setExpandRatio(pnlContenido, 1.0f);
		
		// lblPie
		lblPie = new Label();
		lblPie.setImmediate(false);
		lblPie.setWidth("-1px");
		lblPie.setHeight("-1px");
		lblPie.setValue("Label");
		mainLayoutContainer.addComponent(lblPie);
		mainLayoutContainer.setComponentAlignment(lblPie, new Alignment(24));
		
		return mainLayoutContainer;
	}

	@AutoGenerated
	private VerticalLayout buildPnlCabecera() {
		// common part: create layout
		pnlCabecera = new VerticalLayout();
		pnlCabecera.setImmediate(false);
		pnlCabecera.setWidth("100.0%");
		pnlCabecera.setHeight("-1px");
		pnlCabecera.setMargin(false);
		
		// mnuPrincipal
		mnuPrincipal = new MyMenuBar();
		mnuPrincipal.setImmediate(false);
		mnuPrincipal.setWidth("100.0%");
		mnuPrincipal.setHeight("-1px");
		pnlCabecera.addComponent(mnuPrincipal);
		pnlCabecera.setComponentAlignment(mnuPrincipal, new Alignment(20));
		
		// pnlTitulo
		pnlTitulo = buildPnlTitulo();
		pnlCabecera.addComponent(pnlTitulo);
		
		return pnlCabecera;
	}

	@AutoGenerated
	private VerticalLayout buildPnlTitulo() {
		// common part: create layout
		pnlTitulo = new VerticalLayout();
		pnlTitulo.setImmediate(false);
		pnlTitulo.setWidth("100.0%");
		pnlTitulo.setHeight("40px");
		pnlTitulo.setMargin(false);
		
		// lblTituloPanel
		lblTituloPanel = new Label();
		lblTituloPanel.setImmediate(false);
		lblTituloPanel.setWidth("-1px");
		lblTituloPanel.setHeight("-1px");
		lblTituloPanel.setValue("Label");
		pnlTitulo.addComponent(lblTituloPanel);
		pnlTitulo.setComponentAlignment(lblTituloPanel, new Alignment(48));
		
		return pnlTitulo;
	}

}
